//created on: 24 abr. 2022
package Smartwatch

//list any import classes here.

import model.Bateria;
import model.NivelBateria;

//declare any global variables here


rule "R1 - Low Batery level"
    when
    	$batery:Bateria(capacidadPorcentual > 0, capacidadPorcentual <= 15)
    then
        $batery.setLevel(NivelBateria.Baja);
        update($batery);
end



rule "R2 - Medium Batery level"
    when
    	$batery:Bateria(capacidadPorcentual > 15, capacidadPorcentual <= 70)
    then
        $batery.setLevel(NivelBateria.Media);
        update($batery);
end



rule "R3 - High Batery level"
    when
    	$batery:Bateria(capacidadPorcentual > 70, capacidadPorcentual <= 100)
    then
        $batery.setLevel(NivelBateria.Alta);
        update($batery);
end